package vip.yazilim.libs.springvip.template.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import vip.yazilim.libs.springvip.util.generic.rest.AutoGeneratedRest;


/**
 * To Configuring Swagger
 *
 * @author Emre Sen, 16.08.2019
 * @contact maemresen@yazilim.vip
 */

@Configuration

@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket restApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("Rest API")
                .apiInfo(getApiInfo()).enableUrlTemplating(true).select()
                .apis(RequestHandlerSelectors.basePackage("vip.yazilim.libs.springvip.template.rest"))
                .paths(PathSelectors.any()).build();
    }

    @Bean
    public Docket crudApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("CRUD API")
                .apiInfo(getApiInfo()).enableUrlTemplating(true).select()
                .apis(RequestHandlerSelectors.withClassAnnotation(AutoGeneratedRest.class))
                .paths(PathSelectors.any()).build();
    }

    private ApiInfo getApiInfo() {
        ApiInfoBuilder apiInfoBuilder = new ApiInfoBuilder()
                .title("title")
                .description("desc")
                .version("1.0");
        return apiInfoBuilder.build();
    }
}
