package vip.yazilim.springvipexamples.config

import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import springfox.documentation.builders.ApiInfoBuilder
import springfox.documentation.builders.PathSelectors
import springfox.documentation.builders.RequestHandlerSelectors
import springfox.documentation.service.ApiInfo
import springfox.documentation.spi.DocumentationType
import springfox.documentation.spring.web.plugins.Docket
import springfox.documentation.swagger2.annotations.EnableSwagger2
import vip.yazilim.libs.springvip.util.generic.rest.AutoGeneratedRest


/**
 *
 * @author maemresen - maemresen@yazilim.vip
 * 12/30/2020
 */
@Configuration
@EnableSwagger2
class SwaggerConfig {

    @Bean
    fun restApi(): Docket {
        return Docket(DocumentationType.SWAGGER_2)
            .groupName("Rest API")
            .apiInfo(getApiInfo()).enableUrlTemplating(true).select()
            .apis(RequestHandlerSelectors.basePackage("vip.yazilim.springvipexamples"))
            .paths(PathSelectors.any()).build()
    }

    @Bean
    fun crudApi(): Docket {
        return Docket(DocumentationType.SWAGGER_2)
            .groupName("CRUD API")
            .apiInfo(getApiInfo()).enableUrlTemplating(true).select()
            .apis(RequestHandlerSelectors.withClassAnnotation(AutoGeneratedRest::class.java))
            .paths(PathSelectors.any()).build()
    }

    private fun getApiInfo(): ApiInfo {
        val apiInfoBuilder = ApiInfoBuilder()
            .title("title")
            .description("desc")
            .version("1.0")
        return apiInfoBuilder.build()
    }
}